# Database configuration file for development and testing w/ ActiveRecord or DataMapper/DataObjects.

# NOTE: Our Capistrano deployment replaces this file with a configuration file pulled in from outside the repository.
# NOTE: This defines the default DataMapper connection; other connections can be defined.


default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: APP_NAME_development
  password:
  host: localhost

test:
  <<: *default
  database: APP_NAME_test
  password:
  host: localhost
